server.sh: Specify BDM source type
For some reason, this has started failing with the following error:

  BadRequestException: 400: Client Error for url:
  https://38.102.83.157:13774/v2.1/servers, Block Device Mapping is
  Invalid: Invalid device UUID.

I don't know what has changed under the hood, as I can't see recent
changes to either OSC or Nova that could have triggered this, but the
solution is thankfully rather simple.

Signed-off-by: Stephen Finucane <stephenfin@redhat.com>